export const ENV_VARS = {
  PUBLIC_PROJECT_ID: import.meta.env.VITE_PUBLIC_PROJECT_ID || "",
  WORDLE_TOKEN_ANVIL_ADDRESS: import.meta.env.VITE_WORDLE_TOKEN_ANVIL_ADDRESS || "",
  WORDLE_GAME_ANVIL_ADDRESS: import.meta.env.VITE_WORDLE_GAME_ANVIL_ADDRESS || "",
  WORDLE_TOKEN_SEPOLIA_ADDRESS: import.meta.env.VITE_WORDLE_TOKEN_SEPOLIA_ADDRESS || "",
  WORDLE_GAME_SEPOLIA_ADDRESS: import.meta.env.VITE_WORDLE_GAME_SEPOLIA_ADDRESS || ""
};

export const CHAIN_ID = {
  anvil: 31337,
  sepolia: 11155111
};

export const TOKEN_DECIMALS = 18;
export const NUMBER_OF_GUESSES = 5;
